<a href="https://colab.research.google.com/github/rylp/prez/blob/master/potus.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [171]:
#IMPORTING NECCESSARY STUFF

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [172]:
#CREATING DATAFRAME

#METHOD-1
#url='https://raw.githubusercontent.com/rylp/prez/master/1976-2016-president.csv'
#df=pd.read_csv(url)

#METHOD-2
df=pd.read_csv('1976-2016-president.csv')

df.head(10)

,year,state,state_po,state_fips,state_cen,state_ic,office,candidate,party,writein,candidatevotes,totalvotes,version,notes
0,1976,Alabama,AL,1,63,41,US President,"Carter, Jimmy",democrat,False,659170,1182850,20171015,NaN
1,1976,Alabama,AL,1,63,41,US President,"Ford, Gerald",republican,False,504070,1182850,20171015,NaN
2,1976,Alabama,AL,1,63,41,US President,"Maddox, Lester",american independent party,False,9198,1182850,20171015,NaN
3,1976,Alabama,AL,1,63,41,US President,"Bubar, Benjamin """"Ben""""",prohibition,False,6669,1182850,20171015,NaN
4,1976,Alabama,AL,1,63,41,US President,"Hall, Gus",communist party use,False,1954,1182850,20171015,NaN
5,1976,Alabama,AL,1,63,41,US President,"Macbride, Roger",libertarian,False,1481,1182850,20171015,NaN
6,1976,Alabama,AL,1,63,41,US President,NaN,NaN,True,308,1182850,20171015,NaN
7,1976,Alaska,AK,2,94,81,US President,"Ford, Gerald",republican,False,71555,123574,20171015,NaN
8,1976,Alaska,AK,2,94,81,US President,"Carter, Jimmy",democrat,False,44058,123574,20171015,NaN
9,1976,Alaska,AK,2,94,81,US President,"Macbride, Roger",libertarian,False,6785,123574,20171015,NaN

In [173]:
df.shape #There are 3740 rows and 14 columns
df.describe() #general description

,year,state_fips,state_cen,state_ic,candidatevotes,totalvotes,version,notes
count,3740.000000,3740.000000,3740.000000,3740.000000,3.740000e+03,3.740000e+03,3740.0,0.0
mean,1996.021390,28.855882,53.874866,40.006150,3.151389e+05,2.214284e+06,20171015.0,NaN
std,12.586011,15.637863,26.062865,22.756304,7.371322e+05,2.252806e+06,0.0,NaN
min,1976.000000,1.000000,11.000000,1.000000,1.000000e+00,1.235740e+05,20171015.0,NaN
25%,1984.000000,17.000000,33.000000,22.000000,1.498750e+03,6.296560e+05,20171015.0,NaN
50%,1996.000000,28.000000,54.000000,42.000000,8.992000e+03,1.533950e+06,20171015.0,NaN
75%,2008.000000,42.000000,81.000000,61.000000,2.245050e+05,2.808605e+06,20171015.0,NaN
max,2016.000000,56.000000,95.000000,82.000000,8.753788e+06,1.418160e+07,20171015.0,NaN

In [174]:
#REMOVING UNNECESSARY COLUMNS FROM DATASET like office

df[df.office != 'US President']
#now as no data elemnet has anything other than US President for 'office' column, we can delete it

Empty DataFrame
Columns: [year, state, state_po, state_fips, state_cen, state_ic, office, candidate, party, writein, candidatevotes, totalvotes, version, notes]
Index: []

In [175]:
df.drop(['office'],axis=1,inplace=True) 
#using drop() fn with axis=1 to specify column and inplace=True to state that replace the current dataset with this

In [176]:
df
#now columns have become 13
#now, check for 'notes' column

,year,state,state_po,state_fips,state_cen,state_ic,candidate,party,writein,candidatevotes,totalvotes,version,notes
0,1976,Alabama,AL,1,63,41,"Carter, Jimmy",democrat,False,659170,1182850,20171015,NaN
1,1976,Alabama,AL,1,63,41,"Ford, Gerald",republican,False,504070,1182850,20171015,NaN
2,1976,Alabama,AL,1,63,41,"Maddox, Lester",american independent party,False,9198,1182850,20171015,NaN
3,1976,Alabama,AL,1,63,41,"Bubar, Benjamin """"Ben""""",prohibition,False,6669,1182850,20171015,NaN
4,1976,Alabama,AL,1,63,41,"Hall, Gus",communist party use,False,1954,1182850,20171015,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3735,2016,Wyoming,WY,56,83,68,NaN,NaN,True,6904,258788,20171015,NaN
3736,2016,Wyoming,WY,56,83,68,NaN,independent,False,3224,258788,20171015,NaN
3737,2016,Wyoming,WY,56,83,68,Blank Vote,NaN,False,2661,258788,20171015,NaN
3738,2016,Wyoming,WY,56,83,68,"Castle, Darrell L.",constitution party,False,2042,258788,20171015,NaN
3739,2016,Wyoming,WY,56,83,68,Over Vote,NaN,False,278,258788,20171015,NaN

In [177]:
df[df.notes.notnull()]
#so,here we check if there is any data row with 'notes' as notnull. We didnt find any. so delete it

Empty DataFrame
Columns: [year, state, state_po, state_fips, state_cen, state_ic, candidate, party, writein, candidatevotes, totalvotes, version, notes]
Index: []

In [178]:
df.drop(['notes'],axis=1,inplace=True)

In [179]:
df
#now columns have become 13

,year,state,state_po,state_fips,state_cen,state_ic,candidate,party,writein,candidatevotes,totalvotes,version
0,1976,Alabama,AL,1,63,41,"Carter, Jimmy",democrat,False,659170,1182850,20171015
1,1976,Alabama,AL,1,63,41,"Ford, Gerald",republican,False,504070,1182850,20171015
2,1976,Alabama,AL,1,63,41,"Maddox, Lester",american independent party,False,9198,1182850,20171015
3,1976,Alabama,AL,1,63,41,"Bubar, Benjamin """"Ben""""",prohibition,False,6669,1182850,20171015
4,1976,Alabama,AL,1,63,41,"Hall, Gus",communist party use,False,1954,1182850,20171015
...,...,...,...,...,...,...,...,...,...,...,...,...
3735,2016,Wyoming,WY,56,83,68,NaN,NaN,True,6904,258788,20171015
3736,2016,Wyoming,WY,56,83,68,NaN,independent,False,3224,258788,20171015
3737,2016,Wyoming,WY,56,83,68,Blank Vote,NaN,False,2661,258788,20171015
3738,2016,Wyoming,WY,56,83,68,"Castle, Darrell L.",constitution party,False,2042,258788,20171015
3739,2016,Wyoming,WY,56,83,68,Over Vote,NaN,False,278,258788,20171015

In [213]:
dff=df[(df.party == 'democrat') | (df.party == 'republican') | (df.party== 'democratic-farmer-labor')]
#we want the data of the states which went red or blue 
#so now dff becames our dataframe with party='republican' or party=='democrat' data
dff

,year,state,state_po,state_fips,state_cen,state_ic,candidate,party,writein,candidatevotes,totalvotes,version
0,1976,Alabama,AL,1,63,41,"Carter, Jimmy",democrat,False,659170,1182850,20171015
1,1976,Alabama,AL,1,63,41,"Ford, Gerald",republican,False,504070,1182850,20171015
7,1976,Alaska,AK,2,94,81,"Ford, Gerald",republican,False,71555,123574,20171015
8,1976,Alaska,AK,2,94,81,"Carter, Jimmy",democrat,False,44058,123574,20171015
11,1976,Arizona,AZ,4,86,61,"Ford, Gerald",republican,False,418642,742719,20171015
...,...,...,...,...,...,...,...,...,...,...,...,...
3719,2016,West Virginia,WV,54,55,56,"Clinton, Hillary",democrat,False,188794,713051,20171015
3723,2016,Wisconsin,WI,55,35,25,"Trump, Donald J.",republican,False,1405284,2976150,20171015
3724,2016,Wisconsin,WI,55,35,25,"Clinton, Hillary",democrat,False,1382536,2976150,20171015
3732,2016,Wyoming,WY,56,83,68,"Trump, Donald J.",republican,False,174419,258788,20171015
3733,2016,Wyoming,WY,56,83,68,"Clinton, Hillary",democrat,False,55973,258788,20171015

In [215]:
dff[dff.party=='democratic-farmer-labor']
#change the 'democratic-farmer-labour' to 'democrat'

,year,state,state_po,state_fips,state_cen,state_ic,candidate,party,writein,candidatevotes,totalvotes,version
2210,2000,Minnesota,MN,27,41,33,"Gore, Al",democratic-farmer-labor,False,1168266,2438685,20171015
2559,2004,Minnesota,MN,27,41,33,"Kerry, John",democratic-farmer-labor,False,1445014,2828387,20171015
3225,2012,Minnesota,MN,27,41,33,"Obama, Barack H.",democratic-farmer-labor,False,1546167,2936561,20171015

In [219]:
#at index 2210 2559 3225 we have 'democratic-farmer-labour' 
dff.at[2210,'party']='democrat'
dff.at[2559,'party']='democrat'
dff.at[3225,'party']='democrat'
dff

,year,state,state_po,state_fips,state_cen,state_ic,candidate,party,writein,candidatevotes,totalvotes,version
0,1976,Alabama,AL,1,63,41,"Carter, Jimmy",democrat,False,659170,1182850,20171015
1,1976,Alabama,AL,1,63,41,"Ford, Gerald",republican,False,504070,1182850,20171015
7,1976,Alaska,AK,2,94,81,"Ford, Gerald",republican,False,71555,123574,20171015
8,1976,Alaska,AK,2,94,81,"Carter, Jimmy",democrat,False,44058,123574,20171015
11,1976,Arizona,AZ,4,86,61,"Ford, Gerald",republican,False,418642,742719,20171015
...,...,...,...,...,...,...,...,...,...,...,...,...
3719,2016,West Virginia,WV,54,55,56,"Clinton, Hillary",democrat,False,188794,713051,20171015
3723,2016,Wisconsin,WI,55,35,25,"Trump, Donald J.",republican,False,1405284,2976150,20171015
3724,2016,Wisconsin,WI,55,35,25,"Clinton, Hillary",democrat,False,1382536,2976150,20171015
3732,2016,Wyoming,WY,56,83,68,"Trump, Donald J.",republican,False,174419,258788,20171015
3733,2016,Wyoming,WY,56,83,68,"Clinton, Hillary",democrat,False,55973,258788,20171015

In [221]:
#now see if any 'democratic-party-labour' is still left
dff[dff.party=='democratic-farmer-labor']
#now , check 'writein'

Empty DataFrame
Columns: [year, state, state_po, state_fips, state_cen, state_ic, candidate, party, writein, candidatevotes, totalvotes, version]
Index: []

In [222]:
dff[dff.writein] #now, we cant remove this column as they are entries where 'writein'==True

,year,state,state_po,state_fips,state_cen,state_ic,candidate,party,writein,candidatevotes,totalvotes,version
2544,2004,Maryland,MD,24,52,52,Other,democrat,True,7,2384238,20171015
3414,2016,Arizona,AZ,4,86,61,NaN,democrat,True,42,2573165,20171015
3542,2016,Maryland,MD,24,52,52,"Trump, Donald J.",republican,True,259,2781446,20171015
3543,2016,Maryland,MD,24,52,52,"Clinton, Hillary",democrat,True,78,2781446,20171015

In [223]:
#check for version if its same thruout
dff[dff.version != 20171015]

Empty DataFrame
Columns: [year, state, state_po, state_fips, state_cen, state_ic, candidate, party, writein, candidatevotes, totalvotes, version]
Index: []

In [224]:
#so no data row has version != 20171015
#so can delete it 
dff.drop(['version'],axis=1,inplace=True)

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py:4102: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [225]:
dff
#so now 11 cols

,year,state,state_po,state_fips,state_cen,state_ic,candidate,party,writein,candidatevotes,totalvotes
0,1976,Alabama,AL,1,63,41,"Carter, Jimmy",democrat,False,659170,1182850
1,1976,Alabama,AL,1,63,41,"Ford, Gerald",republican,False,504070,1182850
7,1976,Alaska,AK,2,94,81,"Ford, Gerald",republican,False,71555,123574
8,1976,Alaska,AK,2,94,81,"Carter, Jimmy",democrat,False,44058,123574
11,1976,Arizona,AZ,4,86,61,"Ford, Gerald",republican,False,418642,742719
...,...,...,...,...,...,...,...,...,...,...,...
3719,2016,West Virginia,WV,54,55,56,"Clinton, Hillary",democrat,False,188794,713051
3723,2016,Wisconsin,WI,55,35,25,"Trump, Donald J.",republican,False,1405284,2976150
3724,2016,Wisconsin,WI,55,35,25,"Clinton, Hillary",democrat,False,1382536,2976150
3732,2016,Wyoming,WY,56,83,68,"Trump, Donald J.",republican,False,174419,258788
3733,2016,Wyoming,WY,56,83,68,"Clinton, Hillary",democrat,False,55973,258788

In [226]:
dff[dff.candidate.isnull()] #only 1 data row
#delete it from the dataset
dff.drop(index=3414,axis=0,inplace=True)

In [227]:
dff[dff.candidate == 'Other'] #only 1 data row
#delete it from the dataset
dff.drop(index=2544,axis=0,inplace=True)

In [228]:
#resetting our indexes from 0 onwards
dff.reset_index(drop=True) #drop=True is used to drop that previous column of indexes ie 0,1,7,8...

,year,state,state_po,state_fips,state_cen,state_ic,candidate,party,writein,candidatevotes,totalvotes
0,1976,Alabama,AL,1,63,41,"Carter, Jimmy",democrat,False,659170,1182850
1,1976,Alabama,AL,1,63,41,"Ford, Gerald",republican,False,504070,1182850
2,1976,Alaska,AK,2,94,81,"Ford, Gerald",republican,False,71555,123574
3,1976,Alaska,AK,2,94,81,"Carter, Jimmy",democrat,False,44058,123574
4,1976,Arizona,AZ,4,86,61,"Ford, Gerald",republican,False,418642,742719
...,...,...,...,...,...,...,...,...,...,...,...
1119,2016,West Virginia,WV,54,55,56,"Clinton, Hillary",democrat,False,188794,713051
1120,2016,Wisconsin,WI,55,35,25,"Trump, Donald J.",republican,False,1405284,2976150
1121,2016,Wisconsin,WI,55,35,25,"Clinton, Hillary",democrat,False,1382536,2976150
1122,2016,Wyoming,WY,56,83,68,"Trump, Donald J.",republican,False,174419,258788
1123,2016,Wyoming,WY,56,83,68,"Clinton, Hillary",democrat,False,55973,258788

In [229]:
dff[200:800]

,year,state,state_po,state_fips,state_cen,state_ic,candidate,party,writein,candidatevotes,totalvotes
681,1980,Wisconsin,WI,55,35,25,"Reagan, Ronald",republican,False,1088845,2273221
682,1980,Wisconsin,WI,55,35,25,"Carter, Jimmy",democrat,False,981584,2273221
692,1980,Wyoming,WY,56,83,68,"Reagan, Ronald",republican,False,110700,176713
693,1980,Wyoming,WY,56,83,68,"Carter, Jimmy",democrat,False,49427,176713
696,1984,Alabama,AL,1,63,41,"Reagan, Ronald",republican,False,872849,1441713
...,...,...,...,...,...,...,...,...,...,...,...
2663,2004,South Carolina,SC,45,57,48,"Kerry, John",democrat,False,661669,1617700
2669,2004,South Dakota,SD,46,45,37,"Bush, George W.",republican,False,232584,388215
2670,2004,South Dakota,SD,46,45,37,"Kerry, John",democrat,False,149244,388215
2674,2004,Tennessee,TN,47,62,54,"Bush, George W.",republican,False,1384375,2437319
2675,2004,Tennessee,TN,47,62,54,"Kerry, John",democrat,False,1036477,2437319

In [230]:
#Grouping the data according to states
grouped_data_by_state=dff.groupby('state')
grouped_data_by_state.count()

,year,state_po,state_fips,state_cen,state_ic,candidate,party,writein,candidatevotes,totalvotes
state,,,,,,,,,,
Alabama,22,22,22,22,22,22,22,22,22,22
Alaska,22,22,22,22,22,22,22,22,22,22
Arizona,22,22,22,22,22,22,22,22,22,22
Arkansas,22,22,22,22,22,22,22,22,22,22
California,22,22,22,22,22,22,22,22,22,22
Colorado,22,22,22,22,22,22,22,22,22,22
Connecticut,22,22,22,22,22,22,22,22,22,22
Delaware,22,22,22,22,22,22,22,22,22,22
District of Columbia,22,22,22,22,22,22,22,22,22,22
Florida,22,22,22,22,22,22,22,22,22,22
Georgia,22,22,22,22,22,22,22,22,22,22
Hawaii,22,22,22,22,22,22,22,22,22,22
Idaho,22,22,22,22,22,22,22,22,22,22
Illinois,22,22,22,22,22,22,22,22,22,22
Indiana,22,22,22,22,22,22,22,22,22,22
Iowa,22,22,22,22,22,22,22,22,22,22
Kansas,22,22,22,22,22,22,22,22,22,22
Kentucky,22,22,22,22,22,22,22,22,22,22
Louisiana,22,22,22,22,22,22,22,22,22,22
Maine,22,22,22,22,22,22,22,22,22,22
Maryland,24,24,24,24,24,24,24,24,24,24
Massachusetts,22,22,22,22,22,22,22,22,22,22
Michigan,22,22,22,22,22,22,22,22,22,22
Minnesota,22,22,22,22,22,22,22,22,22,22
Mississippi,22,22,22,22,22,22,22,22,22,22
Missouri,22,22,22,22,22,22,22,22,22,22
Montana,22,22,22,22,22,22,22,22,22,22
Nebraska,22,22,22,22,22,22,22,22,22,22
Nevada,22,22,22,22,22,22,22,22,22,22
New Hampshire,22,22,22,22,22,22,22,22,22,22
New Jersey,22,22,22,22,22,22,22,22,22,22
New Mexico,22,22,22,22,22,22,22,22,22,22
New York,22,22,22,22,22,22,22,22,22,22
North Carolina,22,22,22,22,22,22,22,22,22,22
North Dakota,22,22,22,22,22,22,22,22,22,22
Ohio,22,22,22,22,22,22,22,22,22,22
Oklahoma,22,22,22,22,22,22,22,22,22,22
Oregon,22,22,22,22,22,22,22,22,22,22
Pennsylvania,22,22,22,22,22,22,22,22,22,22
Rhode Island,22,22,22,22,22,22,22,22,22,22
South Carolina,22,22,22,22,22,22,22,22,22,22
South Dakota,22,22,22,22,22,22,22,22,22,22
Tennessee,22,22,22,22,22,22,22,22,22,22
Texas,22,22,22,22,22,22,22,22,22,22
Utah,22,22,22,22,22,22,22,22,22,22
Vermont,22,22,22,22,22,22,22,22,22,22
Virginia,22,22,22,22,22,22,22,22,22,22
Washington,22,22,22,22,22,22,22,22,22,22
West Virginia,22,22,22,22,22,22,22,22,22,22
Wisconsin,22,22,22,22,22,22,22,22,22,22
Wyoming,22,22,22,22,22,22,22,22,22,22

In [231]:
#displaying data of Arizona state
grouped_data_by_state.get_group('Arizona')

,year,state,state_po,state_fips,state_cen,state_ic,candidate,party,writein,candidatevotes,totalvotes
11,1976,Arizona,AZ,4,86,61,"Ford, Gerald",republican,False,418642,742719
12,1976,Arizona,AZ,4,86,61,"Carter, Jimmy",democrat,False,295602,742719
347,1980,Arizona,AZ,4,86,61,"Reagan, Ronald",republican,False,529688,873945
348,1980,Arizona,AZ,4,86,61,"Carter, Jimmy",democrat,False,246843,873945
707,1984,Arizona,AZ,4,86,61,"Reagan, Ronald",republican,False,681416,1025897
708,1984,Arizona,AZ,4,86,61,"Mondale, Walter",democrat,False,333854,1025897
1030,1988,Arizona,AZ,4,86,61,"Bush, George H.W.",republican,False,702541,1171873
1031,1988,Arizona,AZ,4,86,61,"Dukakis, Michael",democrat,False,454029,1171873
1320,1992,Arizona,AZ,4,86,61,"Bush, George H.W.",republican,False,572086,1486975
1321,1992,Arizona,AZ,4,86,61,"Clinton, Bill",democrat,False,543050,1486975
1688,1996,Arizona,AZ,4,86,61,"Clinton, Bill",democrat,False,653288,1404405
1689,1996,Arizona,AZ,4,86,61,"Dole, Robert",republican,False,622073,1404405
2055,2000,Arizona,AZ,4,86,61,"Bush, George W.",republican,False,781652,1532016
2056,2000,Arizona,AZ,4,86,61,"Gore, Al",democrat,False,685341,1532016
2422,2004,Arizona,AZ,4,86,61,"Bush, George W.",republican,False,1104294,2012585
2423,2004,Arizona,AZ,4,86,61,"Kerry, John",democrat,False,893524,2012585
2738,2008,Arizona,AZ,4,86,61,"McCain, John",republican,False,1230111,2293475
2739,2008,Arizona,AZ,4,86,61,"Obama, Barack H.",democrat,False,1034707,2293475
3088,2012,Arizona,AZ,4,86,61,"Romney, Mitt",republican,False,1233654,2299254
3089,2012,Arizona,AZ,4,86,61,"Obama, Barack H.",democrat,False,1025232,2299254
3407,2016,Arizona,AZ,4,86,61,"Trump, Donald J.",republican,False,1252401,2573165
3408,2016,Arizona,AZ,4,86,61,"Clinton, Hillary",democrat,False,1161167,2573165

In [232]:
#displaying data of Maryland state
grouped_data_by_state.get_group('Maryland')

,year,state,state_po,state_fips,state_cen,state_ic,candidate,party,writein,candidatevotes,totalvotes
122,1976,Maryland,MD,24,52,52,"Carter, Jimmy",democrat,False,759612,1432273
123,1976,Maryland,MD,24,52,52,"Ford, Gerald",republican,False,672661,1432273
475,1980,Maryland,MD,24,52,52,"Carter, Jimmy",democrat,False,726161,1540496
476,1980,Maryland,MD,24,52,52,"Reagan, Ronald",republican,False,680606,1540496
819,1984,Maryland,MD,24,52,52,"Reagan, Ronald",republican,False,879918,1675873
820,1984,Maryland,MD,24,52,52,"Mondale, Walter",democrat,False,787935,1675873
1126,1988,Maryland,MD,24,52,52,"Bush, George H.W.",republican,False,876167,1714358
1127,1988,Maryland,MD,24,52,52,"Dukakis, Michael",democrat,False,826304,1714358
1450,1992,Maryland,MD,24,52,52,"Clinton, Bill",democrat,False,988571,1984580
1451,1992,Maryland,MD,24,52,52,"Bush, George H.W.",republican,False,707094,1984580
1823,1996,Maryland,MD,24,52,52,"Clinton, Bill",democrat,False,966207,1780870
1824,1996,Maryland,MD,24,52,52,"Dole, Robert",republican,False,681530,1780870
2187,2000,Maryland,MD,24,52,52,"Gore, Al",democrat,False,1144008,2025212
2188,2000,Maryland,MD,24,52,52,"Bush, George W.",republican,False,813827,2025212
2537,2004,Maryland,MD,24,52,52,"Kerry, John",democrat,False,1334493,2384238
2538,2004,Maryland,MD,24,52,52,"Bush, George W.",republican,False,1024703,2384238
2871,2008,Maryland,MD,24,52,52,"Obama, Barack H.",democrat,False,1629467,2631596
2872,2008,Maryland,MD,24,52,52,"McCain, John",republican,False,959862,2631596
3208,2012,Maryland,MD,24,52,52,"Obama, Barack H.",democrat,False,1677844,2707327
3209,2012,Maryland,MD,24,52,52,"Romney, Mitt",republican,False,971869,2707327
3535,2016,Maryland,MD,24,52,52,"Clinton, Hillary",democrat,False,1677928,2781446
3536,2016,Maryland,MD,24,52,52,"Trump, Donald J.",republican,False,943169,2781446
3542,2016,Maryland,MD,24,52,52,"Trump, Donald J.",republican,True,259,2781446
3543,2016,Maryland,MD,24,52,52,"Clinton, Hillary",democrat,True,78,2781446

In [233]:
#displaying data of Massachusetts state
grouped_data_by_state.get_group('Massachusetts')

,year,state,state_po,state_fips,state_cen,state_ic,candidate,party,writein,candidatevotes,totalvotes
124,1976,Massachusetts,MA,25,14,3,"Carter, Jimmy",democrat,False,1429475,2547558
125,1976,Massachusetts,MA,25,14,3,"Ford, Gerald",republican,False,1030276,2547558
479,1980,Massachusetts,MA,25,14,3,"Reagan, Ronald",republican,False,1057631,2524090
480,1980,Massachusetts,MA,25,14,3,"Carter, Jimmy",democrat,False,1053802,2524090
825,1984,Massachusetts,MA,25,14,3,"Reagan, Ronald",republican,False,1310936,2559383
826,1984,Massachusetts,MA,25,14,3,"Mondale, Walter",democrat,False,1239606,2559383
1131,1988,Massachusetts,MA,25,14,3,"Dukakis, Michael",democrat,False,1401415,2632801
1132,1988,Massachusetts,MA,25,14,3,"Bush, George H.W.",republican,False,1194635,2632801
1455,1992,Massachusetts,MA,25,14,3,"Clinton, Bill",democrat,False,1318639,2773664
1456,1992,Massachusetts,MA,25,14,3,"Bush, George H.W.",republican,False,805039,2773664
1830,1996,Massachusetts,MA,25,14,3,"Clinton, Bill",democrat,False,1571509,2556459
1831,1996,Massachusetts,MA,25,14,3,"Dole, Robert",republican,False,718058,2556459
2195,2000,Massachusetts,MA,25,14,3,"Gore, Al",democrat,False,1616487,2733964
2196,2000,Massachusetts,MA,25,14,3,"Bush, George W.",republican,False,878502,2733964
2545,2004,Massachusetts,MA,25,14,3,"Kerry, John",democrat,False,1803800,2927455
2546,2004,Massachusetts,MA,25,14,3,"Bush, George W.",republican,False,1071109,2927455
2878,2008,Massachusetts,MA,25,14,3,"Obama, Barack H.",democrat,False,1904097,3102995
2879,2008,Massachusetts,MA,25,14,3,"McCain, John",republican,False,1108854,3102995
3213,2012,Massachusetts,MA,25,14,3,"Obama, Barack H.",democrat,False,1921290,3184196
3214,2012,Massachusetts,MA,25,14,3,"Romney, Mitt",republican,False,1188314,3184196
3544,2016,Massachusetts,MA,25,14,3,"Clinton, Hillary",democrat,False,1995196,3378821
3545,2016,Massachusetts,MA,25,14,3,"Trump, Donald J.",republican,False,1090893,3378821

In [235]:
#displaying data of Minesota state
grouped_data_by_state.get_group('Minnesota')
#see now there is a bug
# democrats since 2000 have been listed as 'democratic-farmer-labor' in 'Minnesota' so gotta redo it all
#did it 
#now, i want to change those 'democratic-farmer-labor' to 'democrat' for uniformity
#did it

,year,state,state_po,state_fips,state_cen,state_ic,candidate,party,writein,candidatevotes,totalvotes
141,1976,Minnesota,MN,27,41,33,"Carter, Jimmy",democrat,False,1070440,1949931
142,1976,Minnesota,MN,27,41,33,"Ford, Gerald",republican,False,819395,1949931
493,1980,Minnesota,MN,27,41,33,"Carter, Jimmy",democrat,False,954173,2051916
494,1980,Minnesota,MN,27,41,33,"Reagan, Ronald",republican,False,873268,2051916
840,1984,Minnesota,MN,27,41,33,"Mondale, Walter",democrat,False,1036364,2084449
841,1984,Minnesota,MN,27,41,33,"Reagan, Ronald",republican,False,1032603,2084449
1141,1988,Minnesota,MN,27,41,33,"Dukakis, Michael",democrat,False,1109471,2096790
1142,1988,Minnesota,MN,27,41,33,"Bush, George H.W.",republican,False,962337,2096790
1474,1992,Minnesota,MN,27,41,33,"Clinton, Bill",democrat,False,1020997,2347948
1475,1992,Minnesota,MN,27,41,33,"Bush, George H.W.",republican,False,747841,2347948
1846,1996,Minnesota,MN,27,41,33,"Clinton, Bill",democrat,False,1120380,2192492
1847,1996,Minnesota,MN,27,41,33,"Dole, Robert",republican,False,766395,2192492
2210,2000,Minnesota,MN,27,41,33,"Gore, Al",democrat,False,1168266,2438685
2211,2000,Minnesota,MN,27,41,33,"Bush, George W.",republican,False,1109659,2438685
2559,2004,Minnesota,MN,27,41,33,"Kerry, John",democrat,False,1445014,2828387
2560,2004,Minnesota,MN,27,41,33,"Bush, George W.",republican,False,1346695,2828387
2892,2008,Minnesota,MN,27,41,33,"Obama, Barack H.",democrat,False,1573354,2910369
2893,2008,Minnesota,MN,27,41,33,"McCain, John",republican,False,1275409,2910369
3225,2012,Minnesota,MN,27,41,33,"Obama, Barack H.",democrat,False,1546167,2936561
3226,2012,Minnesota,MN,27,41,33,"Romney, Mitt",republican,False,1320225,2936561
3558,2016,Minnesota,MN,27,41,33,"Clinton, Hillary",democrat,False,1367705,2944782
3559,2016,Minnesota,MN,27,41,33,"Trump, Donald J.",republican,False,1322949,2944782